/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#f9f8f3",
        "error-container": "#ffdad6",
        "surface-container-low": "#f6f3f2",
        "on-tertiary-fixed-variant": "#524700",
        "surface-bright": "#fcf9f8",
        "on-surface": "#1c1b1b",
        "inverse-primary": "#c7c7c2",
        "on-primary-fixed": "#1b1c19",
        "secondary": "#645d56",
        "on-secondary-container": "#6a635c",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c6c7c0",
        "surface-dim": "#dcd9d9",
        "surface-tint": "#5e5f5b",
        "on-tertiary-container": "#81721d",
        "inverse-on-surface": "#f3f0ef",
        "secondary-container": "#ebe1d8",
        "on-secondary-fixed-variant": "#4c463f",
        "surface-container-highest": "#e5e2e1",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#464744",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#cec5bc",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "outline": "#767872",
        "surface-container": "#f0eded",
        "on-background": "#1c1b1b",
        "inverse-surface": "#313030",
        "on-tertiary-fixed": "#211b00",
        "tertiary-fixed-dim": "#dac769",
        "primary-fixed": "#e3e3de",
        "on-error": "#ffffff",
        "on-surface-variant": "#454742",
        "primary-fixed-dim": "#c7c7c2",
        "on-secondary-fixed": "#1f1b16",
        "tertiary-fixed": "#f7e382",
        "on-secondary": "#ffffff",
        "primary": "#5e5f5b",
        "secondary-fixed": "#ebe1d8",
        "surface-container-high": "#eae7e7",
        "tertiary": "#6c5e06",
        "surface": "#fcf9f8",
        "background": "#fcf9f8",
        "tertiary-container": "#fff8e6",
        "surface-variant": "#e5e2e1",
        "on-primary-container": "#71726e"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "section-gap": "160px",
        "container-max": "1440px",
        "margin-desktop": "80px",
        "unit": "8px",
        "gutter": "32px",
        "margin-mobile": "24px"
      },
      fontFamily: {
        "display-lg": ["Playfair Display", "serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "label-caps": ["Manrope", "sans-serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "body-md": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "0.05em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "300" }],
        "headline-md": ["32px", { lineHeight: "1.3", letterSpacing: "0.1em", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.2em", fontWeight: "600" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.4", letterSpacing: "0.1em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}